on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - packages.txt
      - .github/workflows/**

name: build

jobs:
  build:
    name: Build packages on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install remotes
        run: Rscript -e "install.packages('remotes')"

      - name: Install drat.builder
        run: Rscript -e "remotes::install_github('richfitz/drat.builder')"

      - name: Update DRAT
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'drat.builder::build()'

      - name: Push results
        run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

