on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - packages.txt
      - .github/workflows/**

name: build

jobs:
  build:
    name: Update DRAT on Ubuntu
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: nbenn/drat.builder

      - name: Install libcurl
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev

      - name: Update DRAT
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'drat.builder::build(check_cran = TRUE)'

      - name: Push results
        run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
