on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - packages.txt
      - .github/workflows/**

name: build & deploy

jobs:
  build:
    name: Update drat repo
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install remotes
        run: Rscript -e "install.packages('remotes')"

      - name: Install libcurl
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install drat.builder
        env:
          GITHUB_PAT: ${{ secrets.NBENN_PUBLIC }}
        run: Rscript -e "remotes::install_github('nbenn/drat.builder')"

      - name: Update drat
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'drat.builder::build(check_cran = TRUE)'

      - name: Push results
        run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v0

  deploy:
    needs: build
    name: Deploy to Github pages

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
